services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: sh -c "
      npm run start:dev"
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
